### ISSUE TITLE
[Bug]: 系统 TTS 不可用导致程序无法启动

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#148]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

下载完后直接打开 ClassIsland

### 期望的行为

在启动时检查系统 TTS 是否可用，不可用切换到 Edge TTS ，无网络时自动禁用。

### 实际结果

在某些把系统 TTS 精简掉的系统中（例如我楼下的四班，他们 LTSB 2016 没有系统 TTS） ，然后只要启动软件就会报错，根本进不去，改不了。（我试出来的，就是这个 BUG）

### 应用版本

1.4.0.0-Firefly-d9be33e

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Qsgz2023ji5ban** [comment]
回四班复现了一下，以下为日志：

```txt
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {D9F6EE60-58C9-458B-88E1-2F908FD7F87C} failed due to the following error: 80040154 没有注册类 (0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.Speech.Internal.ObjectTokens.RegistryDataKey..ctor(String fullPath, SafeRegistryHandle regHandle)
   at System.Speech.Internal.ObjectTokens.RegistryDataKey.Open(String registryPath, Boolean fCreateIfNotExist)
   at System.Speech.Internal.ObjectTokens.ObjectTokenCategory.Create(String sCategoryId)
   at System.Speech.Internal.ObjectTokens.SAPICategories.DefaultDeviceOut()
   at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
   at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToNull()
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputStream(Stream stream, SpeechAudioFormatInfo formatInfo, Boolean headerInfo, Boolean closeStreamOnExit)
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToDefaultAudioDevice()
   at ClassIsland.Services.SpeechService.SystemSpeechService..ctor() in C:\projects\classisland\ClassIsland\Services\SpeechService\SystemSpeechService.cs:line 17
   at ClassIsland.App.<>c.<App_OnStartup>b__26_3(IServiceProvider provider) in C:\projects\classisland\ClassIsland\App.xaml.cs:line 251
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at ClassIsland.Core.IAppHost.GetService[T]() in C:\projects\classisland\ClassIsland.Core\IAppHost.cs:line 13
   at ClassIsland.App.GetService[T]() in C:\projects\classisland\ClassIsland\App.xaml.cs:line 64
   at ClassIsland.App.App_OnStartup(Object sender, StartupEventArgs e) in C:\projects\classisland\ClassIsland\App.xaml.cs:line 357
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Doctor-yoi** [comment]
已在 commit_14c856d1 中修复
