### ISSUE TITLE
[Bug]: 在获取窗口类名时读取错误的内存地址导致崩溃

### ISSUE THREAD

**Issue by HelloWRC** [ClassIsland/ClassIsland#169]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

此 Bug 是随机出现的。

### 期望的行为

应用应稳定运行。

### 实际结果

应用在读取窗口类名时访问了错误的内存地址，导致发生原生崩溃。

### 堆栈跟踪（可选）

```shell
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.String.Ctor(Char*)
   at ClassIsland.NativeWindowHelper.IsForegroundFullScreen(System.Windows.Forms.Screen)
   at ClassIsland.MainWindow+<UpdateTimerOnTick>d__70.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[ClassIsland.MainWindow+<UpdateTimerOnTick>d__70, ClassIsland, Version=1.4.0.2, Culture=neutral, PublicKeyToken=null]](<UpdateTimerOnTick>d__70 ByRef)
   at ClassIsland.MainWindow.UpdateTimerOnTick(System.Object, System.EventArgs)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at ClassIsland.Program.Main(System.String[])
```

### 应用版本

1.4.0.2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Doctor-yoi** [comment]
个人猜测可能是和null值的重构有关

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: HelloWRC ***@***.***>
发送时间: Saturday, June 15, 2024 9:49:51 PM
收件人: ClassIsland/ClassIsland ***@***.***>
抄送: Subscribed ***@***.***>
主题: [ClassIsland/ClassIsland] [Bug]: 在获取窗口类名时读取错误的内存地址导致崩溃 (Issue #169)


检查清单

  *    我已经在 Issues<https://github.com/HelloWRC/ClassIsland/issues?q=> 中找过我要提出的问题，没有找到相同问题的ISSUE。
  *    我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
  *    我已确认我要反馈的问题还没有在 dev<https://github.com/HelloWRC/ClassIsland/commits/dev/> 分支上修复。
  *    我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

重现步骤

此 Bug 是随机出现的。

期望的行为

应用应稳定运行。

实际结果

应用在读取窗口类名时访问了错误的内存地址，导致发生原生崩溃。

堆栈跟踪（可选）

Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.String.Ctor(Char*)
   at ClassIsland.NativeWindowHelper.IsForegroundFullScreen(System.Windows.Forms.Screen)
   at ClassIsland.MainWindow+<UpdateTimerOnTick>d__70.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[ClassIsland.MainWindow+<UpdateTimerOnTick>d__70, ClassIsland, Version=1.4.0.2, Culture=neutral, PublicKeyToken=null]](<UpdateTimerOnTick>d__70 ByRef)
   at ClassIsland.MainWindow.UpdateTimerOnTick(System.Object, System.EventArgs)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at ClassIsland.Program.Main(System.String[])

应用版本

1.4.0.2

操作系统版本

No response

最后一步

  *    我认为上述的描述已经足以详细，以允许开发人员能复现该问题

―

**Comment by HelloWRC** [comment]
https://github.com/ClassIsland/ClassIsland/blob/master/ClassIsland/NativeWindowHelper.cs#L151

可能是这里构造 PWSTR 类型的问题？

**Comment by HelloWRC** [comment]
我试着修复了以下，测试下行不行：https://ci.appveyor.com/project/HelloWRC/classisland-yw873/builds/50071575

**Comment by HelloWRC** [comment]
简单测试了一下，应该没问题了。如果后续还有出现这类问题可以重新打开这个issue反馈。

附测试代码：

``` cs
var str = BuildPWSTR(256); 
var ptr = Marshal.AllocHGlobal(2048);

// 强制进行GC，在修复之前，由于已经超出fixed作用域，所以此时可能会移动构建出来的PWSTR指向的内存，那么在接下来的代码中会导致 AccessViolationException
// 在修复后运行此代码不会出现 AccessViolationException。
GC.Collect(2, GCCollectionMode.Aggressive, true, true);   

GetClassName(win, str, 255);
Marshal.FreeHGlobal(ptr);
var s = str.ToString();
```
