### ISSUE TITLE
[Bug]: 切换屏幕缩放时 ClassIsland 报错

### ISSUE THREAD

**Issue by LyCecilion** [ClassIsland/ClassIsland#217]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

## 在 150% 缩放下切换到 100% 缩放

ClassIsland 正常运行中。

![image](https://github.com/user-attachments/assets/71f31a89-2692-4bcd-9322-b993517fbf51)

将屏幕缩放由 150% 切换到 100%，**有概率**出现托盘图标右键菜单错位的情况。 

![image](https://github.com/user-attachments/assets/0f9790a1-5ab5-4ff2-9b60-ae1495d7e42b)

**有概率**出现应用设置界面标题栏异常宽度的情况。

![image](https://github.com/user-attachments/assets/5cbbb2d0-ac9d-4add-8cd0-9896e6dca7b9)

主界面在更新时、调整停靠位置（上下调整）时会重置其大小到合适的缩放比率。

## 在 100% 缩放下切换到 150% 缩放

ClassIsland 正常运行中。

![image](https://github.com/user-attachments/assets/1af4c3c7-23ed-4ade-a763-e6e194349ea7)

将屏幕缩放由 100% 切换到 150%，**有概率**报错。

![image](https://github.com/user-attachments/assets/8e54f3a7-776d-4c7b-a22c-8c6c9af2092a)

主界面在更新时、调整停靠位置（上下调整）时会重置其大小到合适的缩放比率。

### 期望的行为

考虑到部分小众需求，需要在 ClassIsland 运行的情况下频繁切换分辨率或屏幕缩放，ClassIsland 应处理好这些问题。

### 实际结果

切换分辨率或屏幕缩放可能会导致 ClassIsland 菜单错位、报错或窗口显示异常等问题。

### 堆栈跟踪（可选）

```shell
System.InvalidOperationException: 另一个目标已经连接到此 HostVisual。
   at System.Windows.Media.HostVisual.BeginHosting(VisualTarget target)
   at System.Windows.Media.VisualTarget.BeginHosting()
   at System.Windows.Media.VisualTarget.CreateUCEResources(Channel channel, Channel outOfBandChannel)
   at System.Windows.Media.MediaContext.RegisterICompositionTargetInternal(ICompositionTarget iv)
   at Walterlv.VisualTargetPresentationSource..ctor(HostVisual hostVisual) in D:\a\ClassIsland\ClassIsland\Walterlv\VisualTargetPresentationSource.cs:line 31
   at Walterlv.Windows.AsyncBox.<OnLoaded>b__21_0() in D:\a\ClassIsland\ClassIsland\Walterlv\Windows\AsyncBox.cs:line 135
   at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at Walterlv.Windows.AsyncBox.OnLoaded(Object sender, RoutedEventArgs e) in D:\a\ClassIsland\ClassIsland\Walterlv\Windows\AsyncBox.cs:line 132
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.4.2.2-Griseo-9337800(HEAD) (Core 1.4.0.0)

### 操作系统版本

22631.3880

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by DryIce-cc** [comment]
已复现。

**Comment by DryIce-cc** [comment]
已修复，晚点提pr。
