### ISSUE TITLE
[Bug] 在时间表配置页面中点击“查看此选项的继承情况...”按钮会导致应用崩溃

### ISSUE THREAD

**Issue by RoboMico** [ClassIsland/ClassIsland#267]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

当然是不崩溃了(#｀-_ゝ-)

### 实际结果

“查看此选项的继承情况...”功能不能正常工作，点击此按钮会直接导致应用崩溃

### 重现步骤

1. 在编辑档案界面中新建时间表并添加“上课”时间段
2. 选中时间段，在右侧菜单的“更多选项”中，点击“上课提醒设置”旁边的“查看此选项的继承情况...”按钮
3. 应用崩溃

### 堆栈跟踪（可选）

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassIsland.Services.ProfileAnalyzeService.Walk(AttachableObjectNode node, ICollection`1 foundNodes, Boolean isUp, Boolean isInit) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\ProfileAnalyzeService.cs:line 167
   at ClassIsland.Services.ProfileAnalyzeService.FindNextObjects(AttachableObjectAddress address, String id, Boolean requiresEnabled) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\ProfileAnalyzeService.cs:line 181
   at ClassIsland.Core.Controls.AttachedSettingsControlPresenter.<>c__DisplayClass67_0.<AnalyzeAsync>b__0() in D:\a\ClassIsland\ClassIsland\ClassIsland.Core\Controls\AttachedSettingsControlPresenter.xaml.cs:line 211
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ClassIsland.Core.Controls.AttachedSettingsControlPresenter.AnalyzeAsync() in D:\a\ClassIsland\ClassIsland\ClassIsland.Core\Controls\AttachedSettingsControlPresenter.xaml.cs:line 208
   at ClassIsland.Core.Controls.AttachedSettingsControlPresenter.ButtonShowDetails_OnClick(Object sender, RoutedEventArgs e) in D:\a\ClassIsland\ClassIsland\ClassIsland.Core\Controls\AttachedSettingsControlPresenter.xaml.cs:line 195
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.4.4.0-Griseo-c98d7d8(HEAD) (Core 1.4.0.0)

### 操作系统版本

10.0.22631.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Qsgz2023ji5ban** [comment]
貌似我这边不存在这个Bug，但是可能是没有在别的地方设置的原因（）
![image](https://github.com/user-attachments/assets/504d4cf0-a97f-477a-81db-1c99708865b4)

**Comment by RoboMico** [comment]
@Qsgz2023ji5ban 
> 貌似我这边不存在这个Bug，但是可能是没有在别的地方设置的原因（）

确实，我刚刚去设置里调试了一番，回来就发现这个bug复现不了了（

**Comment by Qsgz2023ji5ban** [comment]
那要不您先挂discussion里面吧，如果有人复现再打开这个issue（）

**Comment by DryIce-cc** [comment]
没选时间表的时候会报灾难，不过可以正常使用；
选了时间表后就不再复现了。
