### ISSUE TITLE
最新版创建临时层课表classisland崩溃

### ISSUE THREAD

**Issue by LCAleksei** [ClassIsland/ClassIsland#328]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

调休创建临时层

### 实际结果

在classisland的“编辑课表”，选择“创建临时层”，当我选择好时间表后，classisland显示应用崩溃（学校seewo，日志无法提供），发生的变化如下：
1.字体崩溃
2.课程消失
重启应用依旧显示崩溃，但其他界面均正常，删除临时层后恢复正常

### 重现步骤

1.classisland菜单的“编辑课表”
2.节面的右上方“创建临时层”
3.选择时间表

### 应用版本

1.5.0.0（最新版）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
```
[2024/9/14 19:24:17] [Critical] ClassIsland.App:
发生严重错误。
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ClassIsland.Core.Controls.LessonsControls.ClassInfoMultiConverter.Convert(Object[] values, Type targetType, Object parameter, CultureInfo culture) in E:\Coding\ClassIsland\ClassIsland.Core\Controls\LessonsControls\ClassInfoMultiConverter.cs:line 42
   at System.Windows.Data.MultiBindingExpression.TransferValue()
   at System.Windows.Data.MultiBindingExpression.UpdateTarget(Boolean includeInnerBindings)
   at System.Windows.Data.MultiBindingExpression.AttachToContext(Boolean lastChance)
   at System.Windows.Data.MultiBindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by DryIce-cc** [comment]
已修复。
