### ISSUE TITLE
[Bug]: 倒计时无法正常显示

### ISSUE THREAD

**Issue by zhgng** [ClassIsland/ClassIsland#376]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

我想让组件栏出现“距离某事件还有某天数”之类的文字。

### 实际结果

![屏幕截图 2024-09-23 014428](https://github.com/user-attachments/assets/2a7c5f74-1210-4828-aa9d-da31c5c9f107)
设置倒计时结束时间后，组件栏没有出现天数。
并且每次打开软件时，都会报错
![014703](https://github.com/user-attachments/assets/c99dfe5a-7a22-4af6-861b-7a504fd9ae31)

### 重现步骤

我不清楚

### 堆栈跟踪（可选）

```shell
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at ClassIsland.Services.LessonsService.ProcessLessons() in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\LessonsService.cs:line 325
   at ClassIsland.Services.LessonsService.MainTimerOnTick(Object sender, EventArgs e) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\LessonsService.cs:line 249
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.5.0.1-Griseo-02d5716(HEAD) (Core 1.4.0.0)

### 操作系统版本

10.0.22631.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
已修复。
