### ISSUE TITLE
[Bug]: 在未知的情况下发生窗体尺寸引起的崩溃

### ISSUE THREAD

**Issue by qzwl** [ClassIsland/ClassIsland#386]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

不崩溃

### 实际结果

崩溃了

### 重现步骤

不清楚，电脑开了一夜。早上解锁他就崩溃了。

### 堆栈跟踪（可选）

```shell
System.Windows.Media.Animation.AnimationException: 无法使用“System.Windows.Media.Animation.DoubleAnimation”在“ClassIsland.MainWindow”上实现“BackgroundWidth”属性的动画。有关详细信息，请查看内部异常。
 ---> System.ArgumentException: 宽度和高度必须为非负值。
   at System.Windows.Size..ctor(Double width, Double height)
   at ClassIsland.Core.Converters.WidthDoubleToRectConverter.Convert(Object[] values, Type targetType, Object parameter, CultureInfo culture) in D:\a\ClassIsland\ClassIsland\ClassIsland.Core\Converters\WidthDoubleToRectConverter.cs:line 48
   at System.Windows.Data.MultiBindingExpression.TransferValue()
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   at System.Windows.Media.Animation.TimeManager.Tick()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.5.0.1-Griseo-02d5716(HEAD) (Core 1.4.0.0)

### 操作系统版本

10.0.22635.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
应用窗体长度为零了？确定啥也没干？

**Comment by MKStoler4096** [comment]
有没有一种玄学的可能，电脑显示器大半夜发疯显示分辨率变成0x0了……

> 别问，问就是我见过……

**Comment by qzwl** [comment]
大概我描述我的使用，我是在自己办公室电脑上使用，屏幕是双屏，一个横屏一个竖屏，均1080P。然后在家用微软远程桌面远程办公室电脑。这个是大概使用环境。接下来说软件配置。提示条在竖屏最上方中间显示。所以有没有可能它在远程桌面的时候副屏没有了。我结束远程桌面后它崩溃的？

**Comment by MKStoler4096** [comment]
估计是

**Comment by HelloWRC** [comment]
已修复。
