### ISSUE TITLE
[Bug]: 在这里输入你的标题

### ISSUE THREAD

**Issue by qzwl** [ClassIsland/ClassIsland#414]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

不崩溃

### 实际结果

崩溃

### 重现步骤

早上来解锁电脑就崩溃了。 是不是不能24小时运行软件的。

### 堆栈跟踪（可选）

```shell
System.ArgumentException: 在指定子级连接到新的父 Visual 之前必须断开与当前父 Visual 的连接。
   at System.Windows.Media.Visual.AddVisualChild(Visual child)
   at Walterlv.Windows.AsyncBox.OnLoaded(Object sender, RoutedEventArgs e) in D:\a\ClassIsland\ClassIsland\ClassIsland.Core\Walterlv\Windows\AsyncBox.cs:line 141
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.5.0.2-Griseo-69afb2e(HEAD) (Core 1.4.0.0)

### 操作系统版本

10.0.22635.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by jiangyin14** [comment]
重复
