### ISSUE TITLE
偶现的内存被释放导致提醒时崩溃

### ISSUE THREAD

**Issue by bywhite0** [ClassIsland/ClassIsland#435]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

内存占用正常

### 实际结果

主界面出现卡顿，汇报的占用内存突然减少（参见日志），提醒事件触发（如下课）时崩溃

*此 Bug 几乎不能复现，但在 .NET 8 环境下出现内存问题感觉还是需要分析一下*

### 重现步骤

1. 安装UIAccess插件并以管理员权限运行ClassIsland
2. 打开一个UWP应用（如「电影与电视」）并全屏
3. 退出全屏，之后主界面出现卡顿
4. 触发下课提醒

### 堆栈跟踪（可选）

```shell
2024/10/19 7:39:48|Information|ClassIsland.Services.LessonsService|发出上课事件。
2024/10/19 7:39:48|Information|ClassIsland.Services.NotificationHostService|请求来源：***
2024/10/19 7:39:48|Information|ClassIsland.MainWindow|处理通知请求：ClassIsland.Controls.NotificationProviders.ClassNotificationProviderControl (null)
2024/10/19 7:39:48|Information|ClassIsland.Views.TopmostEffectWindow|播放顶层特效：ClassIsland.Controls.NotificationEffects.RippleEffect
2024/10/19 7:39:49|Information|ClassIsland.Views.TopmostEffectWindow|结束播放并移除顶层特效：ClassIsland.Controls.NotificationEffects.RippleEffect
2024/10/19 7:40:33|Information|ClassIsland.Services.MemoryWatchDogService|当前内存使用: 241217536
2024/10/19 7:41:32|Information|ClassIsland.Services.WeatherService|获取天气信息：***
2024/10/19 7:41:33|Information|ClassIsland.Services.SettingsService|写入配置文件：LastWeatherInfo
2024/10/19 7:41:33|Information|ClassIsland.Services.SettingsService|写入配置文件：ClassIsland.MainWindow 的 SaveSettings()
2024/10/19 7:41:33|Information|ClassIsland.Services.MemoryWatchDogService|当前内存使用: 243552256
2024/10/19 7:42:33|Information|ClassIsland.Services.MemoryWatchDogService|当前内存使用: 243511296
// 从此处开始主界面出现卡顿，内存被释放
2024/10/19 7:43:33|Information|ClassIsland.Services.MemoryWatchDogService|当前内存使用: 146870272
2024/10/19 7:44:33|Information|ClassIsland.Services.MemoryWatchDogService|当前内存使用: 146997248
2024/10/19 7:45:33|Information|ClassIsland.Services.MemoryWatchDogService|当前内存使用: 147722240
// 此处省略 34 分钟
2024/10/19 8:19:33|Information|ClassIsland.Services.MemoryWatchDogService|当前内存使用: 145285120
2024/10/19 8:19:48|Information|ClassIsland.Services.LessonsService|发出下课事件。
2024/10/19 8:19:48|Information|ClassIsland.Services.NotificationHostService|请求来源：08f0d9c3-c770-4093-a3d0-02f3d90c24bc
2024/10/19 8:19:48|Information|ClassIsland.MainWindow|处理通知请求：ClassIsland.Controls.NotificationProviders.ClassNotificationProviderControl ClassIsland.Controls.NotificationProviders.ClassNotificationProviderControl
2024/10/19 8:19:48|Information|ClassIsland.Views.TopmostEffectWindow|播放顶层特效：ClassIsland.Controls.NotificationEffects.RippleEffect
2024/10/19 8:19:48|Critical|ClassIsland.App|发生严重错误（应用被教学安全模式退出）
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.OnShowWindow(Boolean enableRenderTarget)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024/10/19 8:19:48|Information|Microsoft.Hosting.Lifetime|Application is shutting down...
2024/10/19 8:19:48|Information|ClassIsland.Services.SettingsService|写入配置文件：停止当前应用程序。
2024/10/19 8:19:48|Information|ClassIsland.Services.ProfileService|写入档案文件：./Profiles/Default.json
2024/10/19 8:19:48|Information|ClassIsland.App|App stopping.
2024/10/19 8:19:48|Information|ClassIsland.Services.SettingsService|写入配置文件：停止当前应用程序。
2024/10/19 8:19:48|Information|ClassIsland.Services.ProfileService|写入档案文件：./Profiles/Default.json
2024/10/19 8:19:48|Critical|ClassIsland.App|发生严重错误（应用被教学安全模式退出）
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024/10/19 8:19:48|Information|ClassIsland.Services.SettingsService|写入配置文件：停止当前应用程序。
2024/10/19 8:19:48|Information|ClassIsland.Services.ProfileService|写入档案文件：./Profiles/Default.json
2024/10/19 8:19:48|Critical|ClassIsland.App|发生严重错误（应用被教学安全模式退出）
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024/10/19 8:19:48|Information|ClassIsland.Services.SettingsService|写入配置文件：停止当前应用程序。
2024/10/19 8:19:48|Information|ClassIsland.Services.ProfileService|写入档案文件：./Profiles/Default.json
2024/10/19 8:19:48|Critical|ClassIsland.App|发生严重错误（应用被教学安全模式退出）
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024/10/19 8:19:48|Information|ClassIsland.Services.SettingsService|写入配置文件：停止当前应用程序。
2024/10/19 8:19:48|Information|ClassIsland.Services.ProfileService|写入档案文件：./Profiles/Default.json
2024/10/19 8:19:48|Critical|ClassIsland.App|发生严重错误（应用被教学安全模式退出）
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024/10/19 8:19:48|Information|ClassIsland.Services.SettingsService|写入配置文件：停止当前应用程序。
2024/10/19 8:19:48|Information|ClassIsland.Services.ProfileService|写入档案文件：./Profiles/Default.json
```

### 应用版本

1.5.0.3-Griseo-af0cf67(HEAD) (Core 1.4.0.0)

### 操作系统版本

10.0.18363.1256

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by bywhite0** [comment]
2024/11/17 补充：

在 1.5.2.0 版本添加了轮播组件轮播两个倒计时，于昨天上午再次出现主界面卡顿并且内存被释放的现象。不同的是本次未弹出崩溃窗口而是进程被直接终止。
