### ISSUE TITLE
启动后crash

### ISSUE THREAD

**Issue by WHMyyds** [ClassIsland/ClassIsland#474]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常打开

### 实际结果

崩溃了！
![image](https://github.com/user-attachments/assets/cd2e82df-a4ff-4ceb-a8f7-71a8eb871894)

### 重现步骤

*这个bug是我帮别的班的电教朋友提的，他们班电脑具体有啥情况我不清楚*
1.``ClassIsland_1.5.0.3``突然没法自启动了，注册表和软件设置都调了也没用
2.重新安装后点击软件运行后崩了

### 堆栈跟踪（可选）

```shell
System.UnauthorizedAccessException: Access to the path 'C:\Users\seewo\Desktop\班级\Temp' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at ClassIsland.Services.FileFolderService.CreateFolders() in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\FileFolderService.cs:line 37
   at ClassIsland.App.App_OnStartup(Object sender, StartupEventArgs e) in D:\a\ClassIsland\ClassIsland\ClassIsland\App.xaml.cs:line 261
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.5.0.3-Griseo-02d5716(HEAD) (Core 1.4.0.0)

### 操作系统版本

18363.1316 *希沃修改版*

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
给软件所在目录授予 Everyone 读写权限，并取消只读属性试试看。
