### ISSUE TITLE
同时打开多个 ClassIsland 导致 IPC 广播消息时崩溃

### ISSUE THREAD

**Issue by DryIce-cc** [ClassIsland/ClassIsland#475]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

-

### 实际结果

弹出崩溃窗口。

### 重现步骤

1. 连续点击桌面上的「快速换课」打开 ClassIsland
2. 日志中，数个对等端被连接然后断开（猜测它们是另外几个被同时打开的 ClassIsland）
3. 等待一个跨进程通信路由通知标识符被请求发布（如时间状态变更）
4. 提示崩溃

### 堆栈跟踪（可选）

```shell
2024/10/29 16:32:34|Information|ClassIsland.App|ClassIsland 1.5.1.0-Himeko-ace5031(HEAD) (Core 1.4.0.0)
2024/10/29 16:32:34|Information|ClassIsland.App|初始化应用。
2024/10/29 16:32:34|Information|ClassIsland.App|正在初始化MainWindow。
2024/10/29 16:32:35|Information|ClassIsland.Services.LessonsService|发出上课事件。
2024/10/29 16:32:35|Information|ClassIsland.Services.DiagnosticService|启动共花费 788ms, [0, 2)
2024/10/29 16:32:35|Information|ClassIsland.Services.UriNavigationService|正在 Uri 导航：classisland://app/class-swap
2024/10/29 16:32:35|Information|ClassIsland.Services.IpcService|对等端 120c31ee811a459788c44684d2eb43c5 已连接。
2024/10/29 16:32:35|Information|ClassIsland.Services.IpcService|对等端 88b1c91b13284bd69b0f409a68d805a2 已连接。
2024/10/29 16:32:36|Information|ClassIsland.Services.IpcService|对等端 88b1c91b13284bd69b0f409a68d805a2 已断开。
2024/10/29 16:32:36|Information|ClassIsland.Services.IpcService|对等端 120c31ee811a459788c44684d2eb43c5 已断开。
2024/10/29 16:32:36|Information|ClassIsland.Services.UriNavigationService|正在 Uri 导航：classisland://app/class-swap
2024/10/29 16:32:36|Information|ClassIsland.Services.UriNavigationService|正在 Uri 导航：classisland://app/class-swap



2024/10/29 17:10:00|Information|ClassIsland.Services.LessonsService|发出下课事件。
2024/10/29 17:10:00|Information|ClassIsland.Services.NotificationHostService|请求来源：08f0d9c3-c770-4093-a3d0-02f3d90c24bc
2024/10/29 17:10:00|Information|ClassIsland.MainWindow|处理通知请求：ClassIsland.Controls.NotificationProviders.ClassNotificationProviderControl ClassIsland.Controls.NotificationProviders.ClassNotificationProviderControl
2024/10/29 17:10:00|Critical|ClassIsland.App|发生严重错误。
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassIsland.Services.IpcService.BroadcastNotificationAsync(String id) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\IpcService.cs:line 46
   at ClassIsland.Services.LessonsService.<.ctor>b__113_2(Object _, EventArgs _) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\LessonsService.cs:line 265
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024/10/29 17:10:00|Critical|ClassIsland.App|发生严重错误。
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassIsland.Services.IpcService.BroadcastNotificationAsync(String id) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\IpcService.cs:line 46
   at ClassIsland.Services.LessonsService.<.ctor>b__113_4(Object _, EventArgs _) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\LessonsService.cs:line 269
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)



2024/10/29 17:20:00|Information|ClassIsland.Services.LessonsService|发出上课事件。
2024/10/29 17:20:00|Information|ClassIsland.Services.NotificationHostService|请求来源：08f0d9c3-c770-4093-a3d0-02f3d90c24bc
2024/10/29 17:20:00|Critical|ClassIsland.App|发生严重错误。
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassIsland.Services.IpcService.BroadcastNotificationAsync(String id) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\IpcService.cs:line 46
   at ClassIsland.Services.LessonsService.<.ctor>b__113_2(Object _, EventArgs _) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\LessonsService.cs:line 265
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024/10/29 17:20:00|Critical|ClassIsland.App|发生严重错误。
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassIsland.Services.IpcService.BroadcastNotificationAsync(String id) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\IpcService.cs:line 46
   at ClassIsland.Services.LessonsService.<.ctor>b__113_3(Object _, EventArgs _) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\LessonsService.cs:line 267
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024/10/29 17:20:00|Information|ClassIsland.MainWindow|处理通知请求：ClassIsland.Controls.NotificationProviders.ClassNotificationProviderControl (null)
```

### 应用版本

ClassIsland 1.5.1.0-Himeko-ace5031(HEAD) (Core 1.4.0.0)

### 操作系统版本

只记得是 Windows 10 了

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
未能在 vs 调试时复现，所以不会修（）~技术力不行~

**Comment by 3234374354** [comment]
哥们，你真闲

**Comment by LyCecilion** [comment]
~~向「快速换课」快捷方式进行纵连攻击~~
