### ISSUE TITLE
[Bug]拉取集控清单与策略失败

### ISSUE THREAD

**Issue by jiangyin14** [ClassIsland/ClassIsland#50]
启动软件加载正常，但是显示“今天没有课程”
![image](https://github.com/HelloWRC/ClassIsland/assets/106649516/ad8b4c7b-862f-4e56-b0f2-9930b84b0c50)
疑似本地网络错误，但是拉取数据逻辑上实现有缺陷。

``` fail: ClassIsland.Services.ManagementService[0]
      拉取集控清单与策略失败
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
       ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at ClassIsland.Helpers.WebRequestHelper.GetJson[T](Uri uri) in C:\projects\classisland\ClassIsland\Helpers\WebRequestHelper.cs:line 16
         at ClassIsland.Helpers.WebRequestHelper.SaveJson[T](Uri uri, String path) in C:\projects\classisland\ClassIsland\Helpers\WebRequestHelper.cs:line 23
         at ClassIsland.Services.ManagementService.SetupManagement() in C:\projects\classisland\ClassIsland\Services\ManagementService.cs:line 90 
```

**Comment by jiangyin14** [comment]
本地网络使用浏览器访问配置文件正常，但是软件拉取失败，错误出现在HTTPs中，未加密的HTTP待测试

**Comment by HelloWRC** [comment]
感谢您的反馈。

**Comment by HelloWRC** [comment]
目前在相关的网络请求中添加了失败后重试请求的机制，应该可以缓解这个问题。

**Comment by wjj-8283** [comment]
warn: ClassIsland.Helpers.WebRequestHelper[0]
      Json GET 请求失败（第 3 次重试）https://raw.gitmirror.com/wjj-8283/classisland-mgmt-cfg/master/manifest.json
      System.Text.Json.JsonException: '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 3 | BytePositionInLine: 4.
       ---> System.Text.Json.JsonReaderException: '"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 3 | BytePositionInLine: 4.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
         at ClassIsland.Helpers.WebRequestHelper.GetJson[T](Uri uri, Int32 retries, Nullable`1 cancellationToken) in D:\a\ClassIsland\ClassIsland\ClassIsland\Helpers\WebRequestHelper.cs:line 36
还是无法使用集控，且不是网络问题，三次重试的日志都是这样的

**Comment by Doctor-yoi** [comment]
> warn: ClassIsland.Helpers.WebRequestHelper[0]
> 
>       Json GET 请求失败（第 3 次重试）https://raw.gitmirror.com/wjj-8283/classisland-mgmt-cfg/master/manifest.json
> 
>       System.Text.Json.JsonException: '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 3 | BytePositionInLine: 4.
> 
>        ---> System.Text.Json.JsonReaderException: '"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 3 | BytePositionInLine: 4.
> 
>          at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
> 
>          at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
> 
>          at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
> 
>          at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
> 
>          at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
> 
>          at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
> 
>          --- End of inner exception stack trace ---
> 
>          at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
> 
>          at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
> 
>          at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
> 
>          at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
> 
>          at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
> 
>          at ClassIsland.Helpers.WebRequestHelper.GetJson[T](Uri uri, Int32 retries, Nullable`1 cancellationToken) in D:\a\ClassIsland\ClassIsland\ClassIsland\Helpers\WebRequestHelper.cs:line 36
> 
> 还是无法使用集控，且不是网络问题，三次重试的日志都是这样的

配置文件格式错误
![image](https://github.com/ClassIsland/ClassIsland/assets/106463935/32ade4ba-d4dc-4b9a-8bfb-13a66527b356)
"YiBan"后缺少逗号(,)
