### ISSUE TITLE
三个插件镜像源都连接不上

### ISSUE THREAD

**Issue by MKStoler4096** [ClassIsland/ClassIsland#516]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

能刷新插件

### 实际结果

![image](https://github.com/user-attachments/assets/55e30880-2fdb-4954-8588-dca79b3f328e)
无法SSL，疑似没换ghproxy镜像源？

### 重现步骤

刷新

### 堆栈跟踪（可选）

```shell
[2024/11/17 16:01:24] [Error] ClassIsland.Services.PluginMarketService:
无法加载插件源。
System.Exception: 无法加载插件源：The SSL connection could not be established, see inner exception.
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.Metrics.MetricsHandler.SendAsyncWithMetrics(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at System.Net.WebRequest.GetResponseAsync()
   at Downloader.Request.FetchResponseHeaders(Boolean addRange) in D:\Programming\Personal\Downloader\src\Downloader\Request.cs:line 101
   at Downloader.Request.IsSupportDownloadInRange() in D:\Programming\Personal\Downloader\src\Downloader\Request.cs:line 181
   at Downloader.Request.GetFileSize() in D:\Programming\Personal\Downloader\src\Downloader\Request.cs:line 162
   at Downloader.DownloadService.StartDownload() in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 186
   --- End of inner exception stack trace ---
   at ClassIsland.Services.PluginMarketService.<>c__DisplayClass38_1.<RefreshPluginSourceAsync>b__1(Object sender, AsyncCompletedEventArgs args) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\PluginMarketService.cs:line 118
   at Downloader.DownloadService.OnDownloadFileCompleted(AsyncCompletedEventArgs e) in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 387
   at Downloader.DownloadService.StartDownload() in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 214
   at Downloader.DownloadService.StartDownload() in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 219
   at Downloader.DownloadService.StartDownload(String fileName) in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 178
   at Downloader.DownloadService.DownloadFileTaskAsync(String address, String fileName, CancellationToken cancellationToken) in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 95
   at Downloader.Download.StartAsync(CancellationToken cancellationToken) in D:\Programming\Personal\Downloader\src\Downloader\Download.cs:line 82
   at ClassIsland.Services.PluginMarketService.RefreshPluginSourceAsync() in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\PluginMarketService.cs:line 129
```

### 应用版本

1.5.2.0-Himeko-dde299d(HEAD) (Core 1.4.0.0)

### 操作系统版本

Microsoft Windows 6.3.9600（即Windows 8 With Update 3）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
可能是网不好，可以在插件源管理里切换镜像源解决这个问题。

如果问题还是没有解决，可以在启动 ci 时加上 `-v` 参数打开详细日志输出，然后再把完整日志导出来，以便开发者诊断问题。

**Comment by MKStoler4096** [comment]
切个遍了（）过会导日志（）

**Comment by MKStoler4096** [comment]
[导出的诊断信息.zip](https://github.com/user-attachments/files/17789583/default.zip)这个就是

**Comment by AtriDayo** [comment]
可以尝试通过Watt Toolkit等工具加速GitHub后再看看

**Comment by MKStoler4096** [comment]
没用，win8.1装都装不上

**Comment by HelloWRC** [comment]
日志似乎没有记录详细日志信息，加上 `-v` 参数后再复现问题，收集下详细日志试试看。

**Comment by MKStoler4096** [comment]
豪德

**Comment by MKStoler4096** [comment]
[log-2024-11-22-18-02-45-1.log](https://github.com/user-attachments/files/17868377/log-2024-11-22-18-02-45-1.log)
这个

**Comment by MKStoler4096** [comment]
在同系统 .NET 6.0 的 `1.5.0.4-Griseo-0220b87(HEAD) (Core 1.4.0.0)` 应用中存在同样的问题（可通过更新发现），一样的错误（我记得1.5.0.4开不了详细输出？）：
```log
[2024/11/22 18:12:21] [Error] ClassIsland.Services.AppUpdating.UpdateService:
下载应用更新失败。
System.Exception: 更新下载失败。
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Downloader.Request.FetchResponseHeaders(Boolean addRange) in D:\Programming\Personal\Downloader\src\Downloader\Request.cs:line 101
   at Downloader.Request.IsSupportDownloadInRange() in D:\Programming\Personal\Downloader\src\Downloader\Request.cs:line 181
   at Downloader.Request.GetFileSize() in D:\Programming\Personal\Downloader\src\Downloader\Request.cs:line 162
   at Downloader.DownloadService.StartDownload() in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 186
   --- End of inner exception stack trace ---
   at ClassIsland.Services.AppUpdating.UpdateService.<DownloadUpdateAsync>b__72_1(Object sender, AsyncCompletedEventArgs args) in D:\a\ClassIsland-net6\ClassIsland-net6\ClassIsland\Services\AppUpdating\UpdateService.cs:line 455
   at Downloader.DownloadService.OnDownloadFileCompleted(AsyncCompletedEventArgs e) in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 387
   at Downloader.DownloadService.StartDownload() in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 214
   at Downloader.DownloadService.StartDownload() in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 219
   at Downloader.DownloadService.StartDownload(String fileName) in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 178
   at Downloader.DownloadService.DownloadFileTaskAsync(String address, String fileName, CancellationToken cancellationToken) in D:\Programming\Personal\Downloader\src\Downloader\DownloadService.cs:line 95
   at Downloader.Download.StartAsync(CancellationToken cancellationToken) in D:\Programming\Personal\Downloader\src\Downloader\Download.cs:line 82
   at ClassIsland.Services.AppUpdating.UpdateService.DownloadUpdateAsync() in D:\a\ClassIsland-net6\ClassIsland-net6\ClassIsland\Services\AppUpdating\UpdateService.cs:line 465
```

**Comment by MKStoler4096** [comment]
同时，在 Windows 10 1607（测试的最低版本，别的没试）以上均不存在此问题。

有人测试 Windows 7 下能否正常更新 .NET 6 版本的ci吗？‘

**Comment by HelloWRC** [comment]
``` log
2024/11/22 18:03:16|Information|ClassIsland.Services.PluginMarketService|正在刷新插件源……
2024/11/22 18:03:16|Debug|ClassIsland.Services.PluginMarketService|正在刷新插件源：Default（https://mirror.ghproxy.com/https://github.com/ClassIsland/PluginIndex/releases/download/latest/index.zip）
```

看起来应该正常引用了 ghproxy 的链接，应该是你那边网不好导致无法刷新插件源。

**Comment by MKStoler4096** [comment]
？？？win10下正常啊，也没开挂（）

**Comment by MKStoler4096** [comment]
让我重启过去再测一下

**Comment by MKStoler4096** [comment]
其实 GitHub 源站是能正常下载的，而且能正常访问，估计真的就是原来 mirror.ghproxy.com TLS失败了
![image](https://github.com/user-attachments/assets/61a11993-56b7-44b7-b59c-566dd2bc8f1b)

**Comment by HelloWRC** [comment]
测试了一下，在我这边的 Windows 8.1 上也有这个问题，可能和系统有关，我待会再研究下。

**Comment by MKStoler4096** [comment]
能不能加个`强制下载`，在ssl无法建立时强制下载回文件？
