### ISSUE TITLE
自动时间同步出错（手动没问题）

### ISSUE THREAD

**Issue by wjj-8283** [ClassIsland/ClassIsland#524]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常进行自动时间同步

### 实际结果

有的时候自动同步失败，但人工操作又正常

### 重现步骤

打开ci，坐和放宽，等待自动同步

### 堆栈跟踪（可选）

```shell
[11/26/2024 6:00:56 PM] [Error] ClassIsland.Services.ExactTimeService:
同步时间失败。
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at GuerrillaNtp.NtpClient.Query()
   at ClassIsland.Services.ExactTimeService.Sync() in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\ExactTimeService.cs:line 132
[11/26/2024 9:00:58 PM] [Error] ClassIsland.Services.ExactTimeService:
同步时间失败。
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at GuerrillaNtp.NtpClient.Query()
   at ClassIsland.Services.ExactTimeService.Sync() in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\ExactTimeService.cs:line 132
[11/26/2024 7:10:58 PM] [Error] ClassIsland.Services.ExactTimeService:
同步时间失败。
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at GuerrillaNtp.NtpClient.Query()
   at ClassIsland.Services.ExactTimeService.Sync() in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\ExactTimeService.cs:line 132
[11/26/2024 6:30:57 PM] [Error] ClassIsland.Services.ExactTimeService:
同步时间失败。
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at GuerrillaNtp.NtpClient.Query()
   at ClassIsland.Services.ExactTimeService.Sync() in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\ExactTimeService.cs:line 132

在日志中出现了一个无效的目录（我们教室电脑没有D盘，只有C盘）
```

### 应用版本

1.5.2.0

### 操作系统版本

10.0.26100.2454，Windows 11 IoT企业版LTSC

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Griseo-bh3rd** [comment]
D:\a\ClassIsland??? 这咋看着这么像GitHub workflow的工作路径呢。。。

**Comment by MKStoler4096** [comment]
> D:\a\ClassIsland??? 这咋看着这么像GitHub workflow的工作路径呢。。。

对，这是报的源代码目录。所以这个问题不大。

是不是你们网不好，看起来已经发出请求了，但是超时了（）

**Comment by wjj-8283** [comment]
今天好像又没有任何错误，估计是学校恰好昨天网不好

**Comment by wjj-8283** [comment]
可以关了
