### ISSUE TITLE
奇怪的Bug

### ISSUE THREAD

**Issue by AWDNDWindowsXP** [ClassIsland/ClassIsland#565]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常启动

### 实际结果

崩溃

### 重现步骤

详情我已发到WRC的邮箱

### 堆栈跟踪（可选）

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassIsland.Services.PluginService.InitializePlugins(HostBuilderContext context, IServiceCollection services) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\PluginService.cs:line 101
   at ClassIsland.App.<>c__DisplayClass46_0.<App_OnStartup>b__1(HostBuilderContext context, IServiceCollection services) in D:\a\ClassIsland\ClassIsland\ClassIsland\App.xaml.cs:line 470
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ClassIsland.App.App_OnStartup(Object sender, StartupEventArgs e) in D:\a\ClassIsland\ClassIsland\ClassIsland\App.xaml.cs:line 311
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.5.2.1-Himeko

### 操作系统版本

10.19025.5011

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
更新到1.5.2.2试试？

**Comment by AWDNDWindowsXP** [comment]
> 更新到1.5.2.2试试？
> 
> 以及，卸载一下安装的插件，或者清除一下plugins文件夹？
> 
> （详细步骤能发一下吗？）

GitHub不支持那个文件

**Comment by HelloWRC** [comment]
已修复。
